stages:
    - build
    - test


Build laptop:
    image: alpine
    stage: build
    script: 
          - echo "Building laptops"
          - mkdir build
          - touch build/computer.txt
          - echo "Mainboard" >> build/computer.txt
          - cat build/computer.txt
          - echo "Keyboard" >> build/computer.txt
          - cat build/computer.txt
          - echo "Mouse"
          - cat build/computer.txt
    artifacts:
        paths:
            - build



test laptop:
    image: alpine
    stage: test
    script:
        - test -f build/computer.txt
        - grep "Mainboard" build/computer.txt
        - grep "Mouse" build/computer.txt
    